import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { LenisProvider } from "../components/shared/LenisProvider";

const urbanist = Urbanist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Sebastián Conde - Portfolio",
  description: "Sebastian's Portfolio generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        rel="stylesheet"
        type="text/css"
        href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        precedence="default"
      />
      <body
        className={`${urbanist.className} antialiased bg-zinc-950 text-white`}
      >
        {/* 🚀 Scroll suave activado */}
        <LenisProvider />
        {children}
      </body>
    </html>
  );
}
